services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: maxi
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql